spring:
  application:
    name: spring_boot_demo

  profile:
    active: "staging"
    name: staging
app:
  message: "Staging"
  secret-key: "12345"



  datasource:
    url: jdbc:h2:mem:spring_boot_demo
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secretKey: NGE2YzQ3Njg2OTY5NmJlMWU4YjdmYWFmOTQ5YWE1ZDdhYjUzZjJhMjczZDZjMzM5MTY1YTE5YjEyNjU3OGM2ZTMwYWZkOGQ0YTYyMDc2MDBhOTcxYmNjNGM0NGUwZTQ2
  pippo: "pippoStaging"